---
title: "Tidy Tuesday"
author: "Rohan Krishnan"
date: "2024-08-20"
output: html_document
---

# Load data and basic looks

```{r}
library(tidyverse)
library(ggthemes)
library(gridExtra)

tuesdata <- tidytuesdayR::tt_load('2024-08-20')
monarchData <- tuesdata[1]

monarchData %>% as.data.frame() %>% glimpse()

monarchData <- as.data.frame(monarchData) %>%
  rename( "king_name" = english_monarchs_marriages_df.king_name,
          "king_age" = english_monarchs_marriages_df.king_age,
          "consort_name" = english_monarchs_marriages_df.consort_name,
          "consort_age" = english_monarchs_marriages_df.consort_age,
          "marriage_year" = english_monarchs_marriages_df.year_of_marriage
          )

monarchData %>% dim()

#Look at unique values of columns -- need to do some cleaning
cols <- monarchData %>% colnames()
for(i in cols){
  print(paste(i, ":"))
  print(unique(monarchData[,i]))
}
```

# Clean up column values (remove (?), ?, -)

## Programmatic solution

```{r}
df2 <- monarchData

removeChars <- function(data){
  cols <- colnames(data)
  for(i in cols){
    colList <- data[,i]
    colList <- gsub("(?)", "", colList, fixed = TRUE)
    
    if(i == "consort_age" | i == "king_age" | i == "marriage_year"){
      colList <- gsub("?", NA, colList, fixed = TRUE)
    } else{
      colList <- gsub("?", "", colList, fixed = TRUE)
    }
    
    colList <- gsub("–", NA, colList, fixed = TRUE)
    
    if(i == "consort_age" | i == "king_age" | i == "marriage_year"){
      data[,i] <- as.numeric(colList)
    } else{
      data[,i] <- colList
    }
  }
  return(data)
}

df3 <- removeChars(df2)

```

## Brute force solution

```{r}
df <- monarchData
#gsub not working properly so I'm gonna do a work around
marriage_year <- df$marraige_year
marriage_year <- gsub("(?)", "", marriage_year, fixed = TRUE)
marriage_year <- gsub("–", NA, marriage_year, fixed = TRUE)
marriage_year <- gsub("?", NA, marriage_year, fixed = TRUE)
#marriage_year %>% unique()
df$marriage_year <- as.numeric(marriage_year)

#repeat process for king age
king_age <- df$king_age
king_age <- gsub("(?)", "", king_age, fixed = TRUE)
king_age <- gsub("–", NA, king_age, fixed = TRUE)
king_age <- gsub("?", NA, king_age, fixed = TRUE)
#king_age %>% unique()
df$king_age <- as.numeric(king_age)

#repeat for consort name
consort_name <- df$consort_name
consort_name <- gsub("–", NA, consort_name, fixed = TRUE)
consort_name <- gsub("?", "", consort_name, fixed = TRUE)
#consort_name %>% unique()
df$consort_name <- consort_name

#repeat for consort age
consort_age <- df$consort_age
consort_age <- gsub("?", NA, consort_age, fixed = TRUE)
consort_age <- gsub("–", NA, consort_age, fixed = TRUE)
#consort_age %>% unique()
df$consort_age <- as.numeric(consort_age)
```

```{r}
ageDiffPlot <- df3 %>% 
  mutate(age_diff = king_age - consort_age) %>%
  ggplot(aes(x = king_age, y = age_diff)) + geom_point() + 
  labs(title = "King Age vs Age Difference Between King and Consort (Yikes...)",
       subtitle = "Looks like the older kings were still picking pretty young women.",
       x = "Age of King", 
       y = "Age Difference (Yrs.) Between King and Consort") + 
  ggthemes::theme_clean(); ageDiffPlot
 
avg_consort_age <- mean(df3$consort_age, na.rm = T)
consortVsKingPlot <- df3 %>%
  mutate(age_diff = king_age - consort_age) %>%
  ggplot(aes(x = king_age, y = consort_age, size = age_diff)) + 
  geom_point(alpha = 0.6) + 
  geom_hline(yintercept = mean(avg_consort_age), alpha = 0.6, color = "blue") + 
  annotate("text", x = 7, y = 22, label = "Average Consort Age", size = 3) + 
  ylim(0,60) + 
  xlim(0,60) +
  labs(title = "King Age vs Consort Age",
       subtitle = "Most kings (regardless of age) chose 20 year old consorts (yikes...).",
       size = "Age Difference",
       x = "King Age",
       y = "Consort Age") + 
  ggthemes:: theme_clean();consortVsKingPlot

gridExtra::grid.arrange(ageDiffPlot, consortVsKingPlot, nrow = 1)
```

```{r}
df3 %>%
  group_by(marriage_year) %>%
  summarize(avg_king_age = mean(king_age, na.rm = TRUE),
            avg_consort_age = mean(consort_age, na.rm = TRUE)) %>%
  mutate(avg_diff = avg_king_age - avg_consort_age) %>%
  ggplot(aes(x = marriage_year, y = avg_king_age, color = avg_diff)) + 
  geom_line(lineend = "round", linewidth = 1) +
  labs(title = "King Ages Over Time",
       subtitle = "Some oscillation between larger and smaller age gaps?",
       x = "Marriage Year",
       y = "Average King Age",
       color = "Age Difference") + 
  ggthemes::theme_clean()

df3 %>%
  group_by(marriage_year) %>%
  summarize(avg_king_age = mean(king_age, na.rm = TRUE),
            avg_consort_age = mean(consort_age, na.rm = TRUE)) %>%
  mutate(avg_diff = avg_king_age - avg_consort_age) %>%
  ggplot(aes(x = marriage_year, y = avg_consort_age, color = avg_king_age)) + 
  geom_line(linewidth = 1, lineend = "round") +
  labs(title = "Consort Ages Over Time",
       subtitle = "Chosen consorts got (slightly) older over time", 
       x = "Marriage Year",
       y = "Average Consort Age",
       color = "King Age") + 
  ggthemes::theme_clean()
```

